version: "2"
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.60.0/24

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
  redis:
    image: redis:7.0.4-alpine
    networks:
      - net
  backend:
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
      - REDIS_HOST=redis
    build:
      context: backend
    volumes:
      - ./backend:/app
    networks:
      - net
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    networks:
      - net
