version: "2"
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.60.0/24

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - net
  redis:
    image: redis:7.0.4-alpine
    networks:
      - net
    ports:
      - "127.0.0.1:6379:6379"
  backend:
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
    build:
      context: backend
    volumes:
      - ./backend:/app
      - ./keys:/app/keys
    networks:
      - net
  frontend:
    build:
      context: frontend
    #volumes:
      #- ./frontend:/app
    networks:
      - net
